name: 'Publish Robot Framework test results'
description: 'Publishes the test results of Robot Framework tests.'
inputs:
  output_file:
    description: 'Location of the test results output.xml file.'
    required: true
    default: 'tests/robot_framework/results/output.xml'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          result_report.py
        sparse-checkout-cone-mode: false
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        python result_report.py tests/robot_framework/results/output.xml report.md
        cat report.md >> $GITHUB_STEP_SUMMARY
      shell: bash