name: 'Publish Robot Framework test results'
description: 'Publishes the test results of Robot Framework tests.'
inputs:
  output_file:
    description: 'Location of the test results output.xml file.'
    required: true
    default: 'tests/robot_framework/results/output.xml'
  endpoints:
    description: 'Provide a comma-separated list of endpoints for which the version number should be included in the summary. The endpoints should serve a /version.json.'
    required: false
    default: ''
  username:
    description: 'Optional username for basic authentication on the endpoints.'
    required: false
    default: ''
  password:
    description: 'Optional password for basic authentication on the endpoints.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Parse Robot Framework output
      run: |
        python $GITHUB_ACTION_PATH/result_report.py tests/robot_framework/results/output.xml report.md
        cat report.md >> $GITHUB_STEP_SUMMARY
      shell: bash
      comment:
    - name: Decorate Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: $GITHUB_STEP_SUMMARY
          })
